version: '2.1'

services:
  insurance-company:
    build: microservices/insurance-company-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  insurance-offer:
    build: microservices/insurance-offer-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql2:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  employee:
    build: microservices/employee-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  transaction:
    build: microservices/transaction-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  insurance-company-composite:
    build: microservices/insurance-company-composite-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy

  eureka:
    build: spring-cloud/eureka-server
    mem_limit: 350m

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 350m
    ports:
      - "8081:8081"
  # $ mongo
  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  #pravila sam promene jer imam 2 MySQL baze
  # $ mysql -uroot -h127.0.0.1 -p
  mysql1:
    image: mysql:5.7
    mem_limit: 350m
    environment:
     MYSQL_ROOT_PASSWORD: rootpwd
     MYSQL_USER: user
     MYSQL_HOST: localhost
     MYSQL_PASSWORD: pwd
     MYSQL_DATABASE: transaction-db
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10

  mysql2:
    image: mysql:5.7
    mem_limit: 350m
    environment:
     MYSQL_ROOT_PASSWORD: rootpwd
     MYSQL_USER: user
     MYSQL_HOST: localhost
     MYSQL_PASSWORD: pwd
     MYSQL_DATABASE: insurance-offer-db
    ports:
      - "3308:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.7.8-management
    mem_limit: 350m
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10