server.port: 7000
server.error.include-message: always

app:
  insurance-company-service:
    host: localhost
    port: 7001
  employee-service:
    host: localhost
    port: 7002
  insurance-offer-service:
    host: localhost
    port: 7003
  transaction-service:
    host: localhost
    port: 7004

logging:
    level:
        root: INFO
        se.magnus: DEBUG
